services:
  code:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - ${HOME}/.ssh:/home/vscode/.ssh
    command: sleep infinity
    ports:
      - '8080:4321'
