services:
  portfolio:
    image: node:22.14-alpine3.21
    working_dir: /app
    volumes:
      - .:/app
    command: 'corepack enable pnpm && pnpm config && set store-dir /.pnpm-store && pnpm install && pnpm dev'
    ports:
      - '8080:4321'
