services:
  portfolio:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspaces/portfolio
    volumes:
      - node-modules:/workspaces/portfolio/node_modules
      - pnpm-store:/home/vscode/.pnpm-store
      - ..:/workspaces/portfolio
    environment:
      - WORKDIR=/workspaces/portfolio
      - PNPM_STORE_PATH=/home/vscode/.pnpm-store

volumes:
  pnpm-store: {}
  node-modules: {}
